--- 
after_script: 
  - "codeclimate-test-reporter < ./coverage/lcov.info"
after_success: 
  - "npm run coverage"
before_script: 
  - "npm install"
cache: 
  directories: 
    - node_modules
env: 
  global: 
language: node_js
node_js: 
  - "8.10.0"
notifications: 
  email: false
script: 
  - "npm run test"
  
