language: node_js
node_js:
 - "8"
before_install:
  - npm install -g mocha
  - npm install
  - createuser user -s -U postgres
  - createdb testdb --username=user 
script:
 - npm run test
after_success:
 - npm run coverage
 - npm run codeclimate-report
 - npm run check-coverage
 env:
  #global:
 - NODE_ENV=test