language: node_js
node_js:
 - "6"
notifications:
 email: false
services:
  - postgresql
cache:
 directories:
   - node_modules
before_install:
  - npm install -g mocha
  - npm install
  - createuser user -s -U postgres
  - createdb dbtester --username=user 
script:
 - npm run test
after_success:
 - npm run coverage
 - npm run codeclimate-report
 - npm run check-coverage
env:
  #global:
 - NODE_ENV=test