language: node_js
node_js:
 - "8.10.0"
notifications:
 email: false
cache:
 directories:
   - node_modules
before_script:
 - npm install
 - npm install codeclimate-test-reporter istanbul -g
script:
 - npm run test
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
after_success:
 - npm run coverage
#  - npm run report-coverage
#  - npm run coveralls
env:
  - NODE_ENV=test
  global:
    - CC_TEST_REPORTER_ID=f07127f3df314d9840650484f020f6bcd6007f043956c590fc951318b30c29ef